version: "3"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd
      # POSTGRES_DB: productitemsdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./01-init.sql:/docker-entrypoint-initdb.d/01-init.sql

  node-app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres_data:
